- name: demo on using register
  hosts: all
  tasks:
    - name: execute shell command
      shell: uptime
      register: out

    - name: printing uptime variable
      debug:
        msg: "{{out.stdout}}" 

    - name: Declare variable
      set_facts:
         status: "{{out.rc}}" 

    - name: printing upstatus code
      debug:
       msg: "status of uptime: {{status}}"  
