- name: Demo on using variables
  hosts: all
  vars:
   URL: play.google.com
  tasks:
   - name: print the URL
     debug:
       msg: url variable value is {{URL}}

   - name: print url from task
     debug:
       msg: URL varaible value is {{URL}}
      vars: task.google.com

    - name: print URL from CLI
      debug:
        msg: URL_FROM_CLI = {{URL_FROM_CLI}}